### ISSUE TITLE
Old Message Deletions

### ISSUE THREAD

**Issue by LubricantJam** [DistrictNineHost/Discord-Server-List#1]
When the bit restarts, the old messages remain. Would be good for it to delete the old messages however do not delete all messages in the channel as we use it in our information channel.

**Comment by WardPearce** [comment]
Yea, I was gonna have it just clear the whole channel till I thought of that. Seems like a bit of a pain to get working correctly, but I'll look into it once I've got some spare time.

**Comment by LubricantJam** [comment]
> Yea, I was gonna have it just clear the whole channel till I thought of that. Seems like a bit of a pain to get working correctly, but I'll look into it once I've got some spare time.

Unless it just counts how many messages it creates then deletes that many backwards from the last message ID?

**Comment by WardPearce** [comment]
> Unless it just counts how many messages it creates then deletes that many backwards from the last message ID?

Storing the message IDs into a json file and deleting those getting message objects on start with those IDs is the best way to do it I think. Wouldn't be hard to implement so I'll add it soon :)

**Comment by LubricantJam** [comment]
> > Unless it just counts how many messages it creates then deletes that many backwards from the last message ID?
> 
> Storing the message IDs into a json file and deleting those getting message objects on start with those IDs is the best way to do it I think. Wouldn't be hard to implement so I'll add it soon :)

Beast.

**Comment by WardPearce** [comment]
Having an admin only command like `!addserver ip:port` might be useful too.

**Comment by LubricantJam** [comment]
Soon™️
