### ISSUE TITLE
 bot gets problme after a certain time

### ISSUE THREAD

**Issue by bibi-blocksberg** [DistrictNineHost/Discord-Server-List#2]
===========================================
Name: Csgo-Bot#8026
Community: DistrictNine.Host
Discord.py version: 1.2.3
Source query rewrite version: 2.0.0
===========================================
Task exception was never retrieved
future: <Task finished coro=<background_task() done, defined at /home/administrator/discordbots/Discord-Server-List-master/server-list.py:27> exception=ServerDisconnectedError(None,)>
Traceback (most recent call last):
  File "/home/administrator/discordbots/Discord-Server-List-master/server-list.py", line 37, in background_task
    async with session.get("http://districtnine.host/api/serverquery/?ip={}".format(values["server-ips"])) as r:
  File "/usr/local/lib/python3.6/site-packages/aiohttp/client.py", line 1005, in __aenter__
    self._resp = await self._coro
  File "/usr/local/lib/python3.6/site-packages/aiohttp/client.py", line 497, in _request
    await resp.start(conn)
  File "/usr/local/lib/python3.6/site-packages/aiohttp/client_reqrep.py", line 844, in start
    message, payload = await self._protocol.read()  # type: ignore  # noqa
  File "/usr/local/lib/python3.6/site-packages/aiohttp/streams.py", line 588, in read
    await self._waiter
aiohttp.client_exceptions.ServerDisconnectedError: None

**Comment by WardPearce** [comment]
Is this running the latest update? (pushed about 16 days ago).
Error logs don't tell me anything useful, if this is the latest version I think ik the issue.

**Comment by bibi-blocksberg** [comment]
Yep is the newst version
I think is de update interval  low than 60

Ward <notifications@github.com> schrieb am Di. 6. Aug. 2019 um 05:08:

**Comment by WardPearce** [comment]
try keeping it at 60 or above otherwise it might timeout.

**Comment by bibi-blocksberg** [comment]
Hey bro this failure all time
bot rum 1 h and crash with this failure


https://gyazo.com/1c4bb2ac338e81310e38817089fae40a


Am Do., 8. Aug. 2019 um 05:02 Uhr schrieb Ward <notifications@github.com>:

**Comment by WardPearce** [comment]
Hey, that should be sorted.
Had a ssl issue on our end.
