### ISSUE TITLE
Can u help Bot works for 30 min and crash

### ISSUE THREAD

**Issue by bibi-blocksberg** [DistrictNineHost/Discord-Server-List#3]
===========================================
Name: CsGo Server List#9661
Community: DistrictNine.Host
Discord.py version: 1.2.3
Source query rewrite version: 3.0.0
===========================================
Task exception was never retrieved
future: <Task finished coro=<query_loop() done, defined at run.py:25> exception=RuntimeError('Session is closed',)>
Traceback (most recent call last):
  File "run.py", line 37, in query_loop
    async with session.get("https://districtnine.host/api/serverquery/?ip={}".format(values["server-ips"])) as r:
  File "/usr/local/lib/python3.6/site-packages/aiohttp/client.py", line 1005, in __aenter__
    self._resp = await self._coro
  File "/usr/local/lib/python3.6/site-packages/aiohttp/client.py", line 348, in _request
    raise RuntimeError('Session is closed')
RuntimeError: Session is closed

**Comment by steff1234** [comment]
Name: Server Info#0180
Community: DistrictNine.Host
Discord.py version: 1.2.4
Source query rewrite version: 3.0.0
===========================================
Task exception was never retrieved
future: <Task finished coro=<query_loop() done, defined at run.py:25> exception=RuntimeError('Session is closed',)>
Traceback (most recent call last):
  File "run.py", line 37, in query_loop
    async with session.get("https://districtnine.host/api/serverquery/?ip={}".format(values["server-ips"])) as r:
  File "/home/csgo/.local/lib/python3.6/site-packages/aiohttp/client.py", line 1012, in __aenter__
    self._resp = await self._coro
  File "/home/csgo/.local/lib/python3.6/site-packages/aiohttp/client.py", line 357, in _request
    raise RuntimeError('Session is closed')
RuntimeError: Session is closed




I get the same error. :(

**Comment by WardPearce** [comment]
I'll get onto fixing this once I wake up and I'll also stress test it a bit as well.
Most likely a error with the aiohttp session...

**Comment by bibi-blocksberg** [comment]
> I'll get onto fixing this once I wake up and I'll also stress test it a bit as well.
> Most likely a error with the aiohttp session...



could you also delete the automatic messages from the channel and the offered rebid and does not go offline 
<3

**Comment by WardPearce** [comment]
Try the latest push & tell me if it's working fine

**Comment by WardPearce** [comment]
Assuming bot is working fine over long periods of time now, just reopen this issue if the issues persists.
